steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/chatbotapp-308201/chatbotapp:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/chatbotapp-308201/chatbotapp:$COMMIT_SHA']
  
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'chatbotapp', '--region=australia-southeast1', '--platform=managed', '--image=gcr.io/chatbotapp-308201/chatbotapp:$COMMIT_SHA']
